-- =============================================================================
-- iDrive CDO Car Rental - application schema (PostgreSQL 15+ / Supabase)
--
-- Mirrors the live Supabase database: tables, constraints, indexes, trigger
-- functions, triggers, reporting views and row level security.
--
-- users.email_verified_at and users.remember_token are required by Laravel's
-- email verification and "remember me" login.
--
-- The migration 2026_10_05_000001_create_idrive_schema runs this file on a
-- PostgreSQL database that does not have a `users` table yet. It can also be
-- pasted into the Supabase SQL editor of an empty project.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- -----------------------------------------------------------------------------
-- Trigger functions
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $function$;

CREATE OR REPLACE FUNCTION public.fn_bookings_before_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_capacity INTEGER;
  v_role     TEXT;
BEGIN
  SELECT capacity INTO v_capacity FROM vehicles WHERE vehicle_id = NEW.vehicle_id;
  IF NEW.number_of_passengers > v_capacity THEN
    RAISE EXCEPTION 'Passengers exceed this vehicle''s capacity.';
  END IF;

  SELECT role INTO v_role FROM users WHERE user_id = NEW.user_id;
  IF v_role <> 'customer' THEN
    RAISE EXCEPTION 'Bookings must belong to a customer account.';
  END IF;
  RETURN NEW;
END $function$;

CREATE OR REPLACE FUNCTION public.fn_bookings_before_update()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.status <> OLD.status AND NOT (
       (OLD.status = 'pending'          AND NEW.status IN ('confirmed','rejected','cancelled'))
    OR (OLD.status = 'confirmed'        AND NEW.status IN ('ongoing','cancelled','return_requested'))
    OR (OLD.status = 'ongoing'          AND NEW.status IN ('completed','return_requested'))
    OR (OLD.status = 'return_requested' AND NEW.status IN ('completed','ongoing'))
  ) THEN
    RAISE EXCEPTION 'That status change is not allowed.';
  END IF;
  RETURN NEW;
END $function$;

CREATE OR REPLACE FUNCTION public.fn_drivers_before_write()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_role TEXT;
BEGIN
  IF NEW.user_id IS NOT NULL THEN
    SELECT role INTO v_role FROM users WHERE user_id = NEW.user_id;
    IF v_role <> 'driver' THEN
      RAISE EXCEPTION 'Linked login must have the driver role.';
    END IF;
  END IF;
  RETURN NEW;
END $function$;

CREATE OR REPLACE FUNCTION public.fn_payments_before_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_status TEXT;
BEGIN
  SELECT status INTO v_status FROM bookings WHERE booking_id = NEW.booking_id;
  IF v_status IN ('cancelled','rejected') THEN
    RAISE EXCEPTION 'This booking cannot be paid.';
  END IF;
  RETURN NEW;
END $function$;

CREATE OR REPLACE FUNCTION public.fn_ratings_before_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  b_status  TEXT;
  b_user    BIGINT;
  b_vehicle BIGINT;
BEGIN
  SELECT status, user_id, vehicle_id INTO b_status, b_user, b_vehicle
  FROM bookings WHERE booking_id = NEW.booking_id;

  IF b_status <> 'completed' THEN
    RAISE EXCEPTION 'Rate the car after the trip is completed.';
  END IF;
  IF b_user <> NEW.user_id THEN
    RAISE EXCEPTION 'Only the renter can rate this car.';
  END IF;
  IF b_vehicle <> NEW.vehicle_id THEN
    RAISE EXCEPTION 'Rating vehicle must match the booked vehicle.';
  END IF;
  RETURN NEW;
END $function$;

-- -----------------------------------------------------------------------------
-- Accounts
-- -----------------------------------------------------------------------------

CREATE TABLE public.users (
  user_id             bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code                varchar(40)  NOT NULL,
  email               varchar(120) NOT NULL,
  password_hash       varchar(255) NOT NULL,
  password_salt       varchar(64),
  role                varchar(10)  NOT NULL DEFAULT 'customer',
  first_name          varchar(40)  NOT NULL,
  last_name           varchar(40)  NOT NULL,
  phone               varchar(15)  NOT NULL,
  address             varchar(120),
  department          varchar(60),
  license_no          varchar(30),
  license_expiry      date,
  avatar              text,
  status              varchar(10)  NOT NULL DEFAULT 'active',
  age_confirmed_at    timestamptz,
  terms_accepted_at   timestamptz,
  password_changed_at timestamptz,
  created_at          timestamptz  NOT NULL DEFAULT now(),
  updated_at          timestamptz  NOT NULL DEFAULT now(),
  email_verified_at   timestamptz,
  remember_token      varchar(100),
  CONSTRAINT users_pkey PRIMARY KEY (user_id),
  CONSTRAINT uq_users_code UNIQUE (code),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT ck_users_email CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
  CONSTRAINT ck_users_license CHECK (license_no IS NULL OR license_no ~* '^[A-Z0-9][A-Z0-9-]{5,19}$'),
  CONSTRAINT ck_users_phone CHECK (phone ~ '^09[0-9]{9}$'),
  CONSTRAINT ck_users_role CHECK (role IN ('customer', 'driver', 'staff', 'admin')),
  CONSTRAINT ck_users_status CHECK (status IN ('active', 'disabled'))
);
CREATE INDEX ix_users_role_status ON public.users (role, status);

CREATE TABLE public.user_sessions (
  session_id   char(32)    NOT NULL,
  user_id      bigint      NOT NULL,
  role         varchar(10) NOT NULL,
  csrf_token   varchar(64),
  ip_address   varchar(45),
  user_agent   varchar(255),
  issued_at    timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  expires_at   timestamptz NOT NULL,
  revoked_at   timestamptz,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (session_id),
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES public.users (user_id) ON DELETE CASCADE,
  CONSTRAINT ck_sessions_role CHECK (role IN ('customer', 'driver', 'staff', 'admin')),
  CONSTRAINT ck_sessions_window CHECK (expires_at > issued_at)
);
CREATE INDEX ix_sessions_expires ON public.user_sessions (expires_at);
CREATE INDEX ix_sessions_user ON public.user_sessions (user_id);

CREATE TABLE public.login_lockouts (
  email_hash     char(64)    NOT NULL,
  failed_count   smallint    NOT NULL DEFAULT 0,
  last_failed_at timestamptz,
  locked_until   timestamptz,
  CONSTRAINT login_lockouts_pkey PRIMARY KEY (email_hash)
);

-- -----------------------------------------------------------------------------
-- Catalog
-- -----------------------------------------------------------------------------

CREATE TABLE public.locations (
  location_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name        varchar(80) NOT NULL,
  is_active   boolean     NOT NULL DEFAULT true,
  sort_order  smallint    NOT NULL DEFAULT 0,
  CONSTRAINT locations_pkey PRIMARY KEY (location_id),
  CONSTRAINT uq_locations_name UNIQUE (name)
);

CREATE TABLE public.addons (
  addon_id   smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code       varchar(20)   NOT NULL,
  name       varchar(60)   NOT NULL,
  daily_rate numeric(10,2) NOT NULL,
  is_active  boolean       NOT NULL DEFAULT true,
  CONSTRAINT addons_pkey PRIMARY KEY (addon_id),
  CONSTRAINT uq_addons_code UNIQUE (code),
  CONSTRAINT ck_addons_rate CHECK (daily_rate >= 0)
);

CREATE TABLE public.vehicles (
  vehicle_id     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code           varchar(40)   NOT NULL,
  name           varchar(60)   NOT NULL,
  brand          varchar(30)   NOT NULL,
  model          varchar(30)   NOT NULL,
  year_model     smallint      NOT NULL,
  year_purchased smallint,
  type           varchar(10)   NOT NULL,
  transmission   varchar(10)   NOT NULL,
  fuel           varchar(10)   NOT NULL,
  capacity       smallint      NOT NULL DEFAULT 5,
  luggage        smallint      NOT NULL DEFAULT 2,
  mileage        integer       NOT NULL DEFAULT 0,
  daily_rate     numeric(10,2) NOT NULL,
  plate_number   varchar(12)   NOT NULL,
  image          varchar(300),
  description    varchar(400),
  status         varchar(12)   NOT NULL DEFAULT 'available',
  created_at     timestamptz   NOT NULL DEFAULT now(),
  updated_at     timestamptz   NOT NULL DEFAULT now(),
  deleted_at     timestamptz,
  CONSTRAINT vehicles_pkey PRIMARY KEY (vehicle_id),
  CONSTRAINT uq_vehicles_code UNIQUE (code),
  CONSTRAINT uq_vehicles_plate UNIQUE (plate_number),
  CONSTRAINT ck_vehicles_capacity CHECK (capacity >= 1 AND capacity <= 30),
  CONSTRAINT ck_vehicles_fuel CHECK (fuel IN ('Gasoline', 'Diesel')),
  CONSTRAINT ck_vehicles_plate CHECK (plate_number ~* '^[A-Z0-9]{2,4}-?[0-9]{3,4}$'),
  CONSTRAINT ck_vehicles_rate CHECK (daily_rate >= 500),
  CONSTRAINT ck_vehicles_status CHECK (status IN ('available', 'maintenance')),
  CONSTRAINT ck_vehicles_transmission CHECK (transmission IN ('Automatic', 'Manual')),
  CONSTRAINT ck_vehicles_type CHECK (type IN ('Sedan', 'SUV', 'Van', 'Pickup')),
  CONSTRAINT ck_vehicles_year CHECK (year_model >= 1990 AND year_model <= 2100),
  CONSTRAINT ck_vehicles_year_purchased CHECK (year_purchased IS NULL OR (year_purchased >= 1990 AND year_purchased <= 2100))
);
CREATE INDEX ix_vehicles_brand ON public.vehicles (brand);
CREATE INDEX ix_vehicles_status_type ON public.vehicles (status, type);

CREATE TABLE public.vehicle_features (
  vehicle_feature_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vehicle_id         bigint      NOT NULL,
  feature            varchar(40) NOT NULL,
  sort_order         smallint    NOT NULL DEFAULT 0,
  CONSTRAINT vehicle_features_pkey PRIMARY KEY (vehicle_feature_id),
  CONSTRAINT uq_vehicle_features UNIQUE (vehicle_id, feature),
  CONSTRAINT fk_vehicle_features_vehicle FOREIGN KEY (vehicle_id) REFERENCES public.vehicles (vehicle_id) ON DELETE CASCADE
);

CREATE TABLE public.drivers (
  driver_id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code                varchar(40) NOT NULL,
  user_id             bigint,
  full_name           varchar(80) NOT NULL,
  driver_license      varchar(30) NOT NULL,
  type_driver_license varchar(30) NOT NULL DEFAULT 'Professional',
  license_expiry      date        NOT NULL,
  phone               varchar(15),
  status              varchar(10) NOT NULL DEFAULT 'active',
  duty_status         varchar(10) NOT NULL DEFAULT 'regular',
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  deleted_at          timestamptz,
  CONSTRAINT drivers_pkey PRIMARY KEY (driver_id),
  CONSTRAINT uq_drivers_code UNIQUE (code),
  CONSTRAINT uq_drivers_user UNIQUE (user_id),
  CONSTRAINT uq_drivers_license UNIQUE (driver_license),
  CONSTRAINT fk_drivers_user FOREIGN KEY (user_id) REFERENCES public.users (user_id) ON DELETE SET NULL,
  CONSTRAINT ck_drivers_duty_status CHECK (duty_status IN ('regular', 'on_call')),
  CONSTRAINT ck_drivers_phone CHECK (phone IS NULL OR phone ~ '^09[0-9]{9}$'),
  CONSTRAINT ck_drivers_status CHECK (status IN ('active', 'inactive'))
);
CREATE INDEX ix_drivers_status ON public.drivers (status, duty_status);

-- -----------------------------------------------------------------------------
-- Bookings
-- -----------------------------------------------------------------------------

CREATE TABLE public.bookings (
  booking_id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code                 varchar(40)   NOT NULL,
  ref                  varchar(20)   NOT NULL,
  user_id              bigint        NOT NULL,
  vehicle_id           bigint        NOT NULL,
  driver_id            bigint,
  created_by           bigint,
  start_date           date          NOT NULL,
  end_date             date          NOT NULL,
  pickup_time          time          NOT NULL DEFAULT '09:00:00',
  return_time          time          NOT NULL DEFAULT '09:00:00',
  days                 smallint      NOT NULL,
  pickup_location_id   smallint      NOT NULL,
  dropoff_location_id  smallint      NOT NULL,
  number_of_passengers smallint      NOT NULL DEFAULT 1,
  drive_mode           varchar(10)   NOT NULL DEFAULT 'self',
  driver_option        varchar(12) GENERATED ALWAYS AS (
                         CASE WHEN drive_mode = 'chauffeur' THEN 'Chauffeur' ELSE 'Self-drive' END
                       ) STORED,
  fuel_before_rent     varchar(10)   NOT NULL DEFAULT 'Full',
  fuel_upon_return     varchar(10),
  subtotal             numeric(10,2) NOT NULL,
  extras               numeric(10,2) NOT NULL DEFAULT 0,
  total                numeric(10,2) NOT NULL,
  status               varchar(20)   NOT NULL DEFAULT 'pending',
  payment_status       varchar(10)   NOT NULL DEFAULT 'unpaid',
  payment_method       varchar(10),
  notes                varchar(240),
  return_notes         varchar(240),
  date_reserve         timestamptz   NOT NULL DEFAULT now(),
  started_at           timestamptz,
  started_by           bigint,
  return_requested_at  timestamptz,
  return_requested_by  bigint,
  returned_at          timestamptz,
  returned_by          bigint,
  created_at           timestamptz   NOT NULL DEFAULT now(),
  updated_at           timestamptz   NOT NULL DEFAULT now(),
  CONSTRAINT bookings_pkey PRIMARY KEY (booking_id),
  CONSTRAINT uq_bookings_code UNIQUE (code),
  CONSTRAINT uq_bookings_ref UNIQUE (ref),
  CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES public.users (user_id),
  CONSTRAINT fk_bookings_vehicle FOREIGN KEY (vehicle_id) REFERENCES public.vehicles (vehicle_id),
  CONSTRAINT fk_bookings_driver FOREIGN KEY (driver_id) REFERENCES public.drivers (driver_id),
  CONSTRAINT fk_bookings_created_by FOREIGN KEY (created_by) REFERENCES public.users (user_id),
  CONSTRAINT fk_bookings_pickup FOREIGN KEY (pickup_location_id) REFERENCES public.locations (location_id),
  CONSTRAINT fk_bookings_dropoff FOREIGN KEY (dropoff_location_id) REFERENCES public.locations (location_id),
  CONSTRAINT fk_bookings_started_by FOREIGN KEY (started_by) REFERENCES public.users (user_id),
  CONSTRAINT fk_bookings_return_requested_by FOREIGN KEY (return_requested_by) REFERENCES public.users (user_id),
  CONSTRAINT fk_bookings_returned_by FOREIGN KEY (returned_by) REFERENCES public.users (user_id),
  CONSTRAINT ck_bookings_chauffeur CHECK ((drive_mode = 'chauffeur' AND driver_id IS NOT NULL) OR (drive_mode = 'self' AND driver_id IS NULL)),
  CONSTRAINT ck_bookings_confirmed_paid CHECK (status NOT IN ('confirmed', 'ongoing', 'return_requested', 'completed') OR payment_status = 'paid'),
  CONSTRAINT ck_bookings_dates CHECK (end_date > start_date),
  CONSTRAINT ck_bookings_days CHECK (days >= 1 AND days <= 30 AND days = (end_date - start_date)),
  CONSTRAINT ck_bookings_drive_mode CHECK (drive_mode IN ('self', 'chauffeur')),
  CONSTRAINT ck_bookings_fuel_before CHECK (fuel_before_rent IN ('Full', '3/4', '1/2', '1/4', 'Reserve', 'Empty')),
  CONSTRAINT ck_bookings_fuel_return CHECK (fuel_upon_return IS NULL OR fuel_upon_return IN ('Full', '3/4', '1/2', '1/4', 'Reserve', 'Empty')),
  CONSTRAINT ck_bookings_money CHECK (subtotal >= 0 AND extras >= 0 AND total = (subtotal + extras)),
  CONSTRAINT ck_bookings_paid_method CHECK (payment_status = 'unpaid' OR payment_method IS NOT NULL),
  CONSTRAINT ck_bookings_passengers CHECK (number_of_passengers >= 1 AND number_of_passengers <= 30),
  CONSTRAINT ck_bookings_payment_method CHECK (payment_method IS NULL OR payment_method IN ('cash', 'cashless', 'card')),
  CONSTRAINT ck_bookings_payment_status CHECK (payment_status IN ('unpaid', 'paid')),
  CONSTRAINT ck_bookings_ref CHECK (ref ~* '^IDR-[0-9]{8}-[0-9A-F]{3,6}$'),
  CONSTRAINT ck_bookings_status CHECK (status IN ('pending', 'confirmed', 'ongoing', 'return_requested', 'completed', 'rejected', 'cancelled')),
  CONSTRAINT ex_bookings_no_overlap EXCLUDE USING gist (
    vehicle_id WITH =,
    daterange(start_date, end_date, '[)') WITH &&
  ) WHERE (status IN ('pending', 'confirmed', 'ongoing', 'return_requested'))
);
CREATE INDEX ix_bookings_created_by ON public.bookings (created_by);
CREATE INDEX ix_bookings_driver ON public.bookings (driver_id, status);
CREATE INDEX ix_bookings_dropoff ON public.bookings (dropoff_location_id);
CREATE INDEX ix_bookings_payment ON public.bookings (payment_status);
CREATE INDEX ix_bookings_pickup ON public.bookings (pickup_location_id);
CREATE INDEX ix_bookings_return_req_by ON public.bookings (return_requested_by);
CREATE INDEX ix_bookings_returned_by ON public.bookings (returned_by);
CREATE INDEX ix_bookings_started_by ON public.bookings (started_by);
CREATE INDEX ix_bookings_status ON public.bookings (status, created_at);
CREATE INDEX ix_bookings_user ON public.bookings (user_id, created_at);
CREATE INDEX ix_bookings_vehicle_dates ON public.bookings (vehicle_id, start_date, end_date);

CREATE TABLE public.booking_addons (
  booking_id bigint        NOT NULL,
  addon_id   smallint      NOT NULL,
  daily_rate numeric(10,2) NOT NULL,
  days       smallint      NOT NULL,
  line_total numeric(10,2) GENERATED ALWAYS AS (daily_rate * days::numeric) STORED,
  CONSTRAINT booking_addons_pkey PRIMARY KEY (booking_id, addon_id),
  CONSTRAINT fk_booking_addons_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (booking_id) ON DELETE CASCADE,
  CONSTRAINT fk_booking_addons_addon FOREIGN KEY (addon_id) REFERENCES public.addons (addon_id) ON DELETE RESTRICT,
  CONSTRAINT ck_booking_addons_days CHECK (days >= 1 AND days <= 30)
);
CREATE INDEX ix_booking_addons_addon ON public.booking_addons (addon_id);

CREATE TABLE public.booking_renter_documents (
  booking_id      bigint      NOT NULL,
  license_name    varchar(60),
  license_no      varchar(20),
  license_expiry  date,
  license_address varchar(120),
  emergency_phone varchar(15),
  license_photo   text,
  id_type         varchar(20),
  id_number       varchar(30),
  created_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT booking_renter_documents_pkey PRIMARY KEY (booking_id),
  CONSTRAINT fk_renter_docs_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (booking_id) ON DELETE CASCADE,
  CONSTRAINT ck_renter_docs_id CHECK (id_number IS NULL OR id_number ~* '^[A-Z0-9-]{5,30}$'),
  CONSTRAINT ck_renter_docs_id_type CHECK (id_type IS NULL OR id_type IN ('National ID', 'Passport', 'UMID', 'Postal ID', 'Company ID', 'Student ID')),
  CONSTRAINT ck_renter_docs_kind CHECK (
    (id_type IS NOT NULL AND id_number IS NOT NULL)
    OR (license_name IS NOT NULL AND license_no IS NOT NULL AND license_expiry IS NOT NULL
        AND license_address IS NOT NULL AND emergency_phone IS NOT NULL AND license_photo IS NOT NULL)
  ),
  CONSTRAINT ck_renter_docs_license CHECK (license_no IS NULL OR license_no ~* '^[A-Z0-9][A-Z0-9-]{5,19}$'),
  CONSTRAINT ck_renter_docs_phone CHECK (emergency_phone IS NULL OR emergency_phone ~ '^09[0-9]{9}$'),
  CONSTRAINT ck_renter_docs_photo CHECK (license_photo IS NULL OR license_photo ~* '^data:image/(jpeg|jpg|png|webp);base64,')
);

CREATE TABLE public.payments (
  payment_id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code             varchar(40)   NOT NULL,
  booking_id       bigint        NOT NULL,
  amount           numeric(10,2) NOT NULL,
  payment_method   varchar(10)   NOT NULL,
  brand            varchar(20)   NOT NULL,
  account_last4    varchar(4),
  holder           varchar(80),
  reference_number varchar(40)   NOT NULL,
  payment_status   varchar(10)   NOT NULL DEFAULT 'paid',
  payment_date     timestamptz   NOT NULL DEFAULT now(),
  recorded_by      bigint,
  created_at       timestamptz   NOT NULL DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (payment_id),
  CONSTRAINT uq_payments_code UNIQUE (code),
  CONSTRAINT uq_payments_reference UNIQUE (reference_number),
  CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (booking_id) ON DELETE RESTRICT,
  CONSTRAINT fk_payments_recorded_by FOREIGN KEY (recorded_by) REFERENCES public.users (user_id) ON DELETE SET NULL,
  CONSTRAINT ck_payments_amount CHECK (amount > 0),
  CONSTRAINT ck_payments_brand CHECK (
    (payment_method = 'cash' AND brand = 'Cash')
    OR (payment_method = 'cashless' AND brand IN ('GCash', 'Maya', 'GrabPay'))
    OR payment_method = 'card'
  ),
  CONSTRAINT ck_payments_method CHECK (payment_method IN ('cash', 'cashless', 'card')),
  CONSTRAINT ck_payments_status CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded'))
);
CREATE INDEX ix_payments_booking ON public.payments (booking_id);
CREATE INDEX ix_payments_date ON public.payments (payment_date);
CREATE INDEX ix_payments_method ON public.payments (payment_method, brand);
CREATE INDEX ix_payments_recorded_by ON public.payments (recorded_by);
CREATE UNIQUE INDEX uq_payments_one_paid ON public.payments (booking_id) WHERE payment_status = 'paid';

CREATE TABLE public.ratings (
  rating_id  bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code       varchar(40)  NOT NULL,
  booking_id bigint       NOT NULL,
  vehicle_id bigint       NOT NULL,
  user_id    bigint       NOT NULL,
  stars      smallint     NOT NULL,
  comment    varchar(280),
  created_at timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT ratings_pkey PRIMARY KEY (rating_id),
  CONSTRAINT uq_ratings_code UNIQUE (code),
  CONSTRAINT uq_ratings_booking UNIQUE (booking_id),
  CONSTRAINT fk_ratings_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (booking_id) ON DELETE CASCADE,
  CONSTRAINT fk_ratings_user FOREIGN KEY (user_id) REFERENCES public.users (user_id) ON DELETE CASCADE,
  CONSTRAINT fk_ratings_vehicle FOREIGN KEY (vehicle_id) REFERENCES public.vehicles (vehicle_id) ON DELETE CASCADE,
  CONSTRAINT ck_ratings_stars CHECK (stars >= 1 AND stars <= 5)
);
CREATE INDEX ix_ratings_user ON public.ratings (user_id);
CREATE INDEX ix_ratings_vehicle ON public.ratings (vehicle_id, created_at);

-- -----------------------------------------------------------------------------
-- Messaging
-- -----------------------------------------------------------------------------

CREATE TABLE public.message_threads (
  thread_id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code            varchar(40)  NOT NULL,
  kind            varchar(10)  NOT NULL,
  topic           varchar(80)  NOT NULL,
  booking_id      bigint,
  customer_id     bigint,
  customer_name   varchar(80)  NOT NULL,
  customer_email  varchar(120),
  customer_phone  varchar(15),
  status          varchar(10)  NOT NULL DEFAULT 'open',
  unread_staff    boolean      NOT NULL DEFAULT true,
  unread_customer boolean      NOT NULL DEFAULT false,
  legacy_id       varchar(40),
  created_at      timestamptz  NOT NULL DEFAULT now(),
  updated_at      timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT message_threads_pkey PRIMARY KEY (thread_id),
  CONSTRAINT uq_threads_code UNIQUE (code),
  CONSTRAINT uq_threads_booking UNIQUE (booking_id),
  CONSTRAINT uq_threads_legacy UNIQUE (legacy_id),
  CONSTRAINT fk_threads_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (booking_id) ON DELETE SET NULL,
  CONSTRAINT fk_threads_customer FOREIGN KEY (customer_id) REFERENCES public.users (user_id) ON DELETE SET NULL,
  CONSTRAINT ck_threads_kind CHECK (kind IN ('booking', 'contact', 'return')),
  CONSTRAINT ck_threads_status CHECK (status IN ('open', 'closed'))
);
CREATE INDEX ix_threads_customer ON public.message_threads (customer_id, updated_at);
CREATE INDEX ix_threads_email ON public.message_threads (customer_email);
CREATE INDEX ix_threads_unread ON public.message_threads (unread_staff, updated_at);

CREATE TABLE public.thread_messages (
  message_id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code         varchar(40)  NOT NULL,
  thread_id    bigint       NOT NULL,
  from_role    varchar(10)  NOT NULL,
  from_user_id bigint,
  from_name    varchar(80)  NOT NULL,
  body         varchar(500) NOT NULL,
  sent_at      timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT thread_messages_pkey PRIMARY KEY (message_id),
  CONSTRAINT uq_messages_code UNIQUE (code),
  CONSTRAINT fk_messages_thread FOREIGN KEY (thread_id) REFERENCES public.message_threads (thread_id) ON DELETE CASCADE,
  CONSTRAINT fk_messages_user FOREIGN KEY (from_user_id) REFERENCES public.users (user_id) ON DELETE SET NULL,
  CONSTRAINT ck_messages_role CHECK (from_role IN ('customer', 'staff'))
);
CREATE INDEX ix_messages_thread ON public.thread_messages (thread_id, sent_at);
CREATE INDEX ix_messages_user ON public.thread_messages (from_user_id);

-- -----------------------------------------------------------------------------
-- Fleet operations
-- -----------------------------------------------------------------------------

CREATE TABLE public.vehicle_registrations (
  registration_id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code                  varchar(40) NOT NULL,
  vehicle_id            bigint      NOT NULL,
  plate_number          varchar(12) NOT NULL,
  renewal_scheduled_day smallint,
  next_reg_renewal      date        NOT NULL,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT vehicle_registrations_pkey PRIMARY KEY (registration_id),
  CONSTRAINT uq_registrations_code UNIQUE (code),
  CONSTRAINT uq_registrations_vehicle UNIQUE (vehicle_id),
  CONSTRAINT fk_registrations_vehicle FOREIGN KEY (vehicle_id) REFERENCES public.vehicles (vehicle_id) ON DELETE CASCADE,
  CONSTRAINT ck_registrations_day CHECK (renewal_scheduled_day IS NULL OR (renewal_scheduled_day >= 1 AND renewal_scheduled_day <= 31))
);
CREATE INDEX ix_registrations_due ON public.vehicle_registrations (next_reg_renewal);

CREATE TABLE public.telemetry_readings (
  telemetry_id            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vehicle_id              bigint        NOT NULL,
  brand                   varchar(30)   NOT NULL,
  reading_time            timestamp     NOT NULL,
  reading_hour            smallint GENERATED ALWAYS AS (EXTRACT(hour FROM reading_time)::smallint) STORED,
  reading_day_of_week     smallint GENERATED ALWAYS AS ((EXTRACT(isodow FROM reading_time) - 1)::smallint) STORED,
  odometer_reading        numeric(10,1) NOT NULL,
  engine_temp_c           numeric(6,2)  NOT NULL,
  engine_rpm              numeric(7,1)  NOT NULL,
  oil_pressure_psi        numeric(6,2)  NOT NULL,
  coolant_temp_c          numeric(6,2)  NOT NULL,
  fuel_level_percent      numeric(5,2)  NOT NULL,
  fuel_consumption_lph    numeric(6,2)  NOT NULL,
  engine_load_percent     numeric(5,2)  NOT NULL,
  throttle_pos_percent    numeric(5,2)  NOT NULL,
  air_flow_rate_gps       numeric(7,2)  NOT NULL,
  exhaust_gas_temp_c      numeric(6,2)  NOT NULL,
  vibration_level         numeric(5,2)  NOT NULL,
  engine_hours            numeric(9,1)  NOT NULL,
  brake_fluid_level_psi   numeric(7,2)  NOT NULL,
  brake_pad_wear_mm       numeric(5,2)  NOT NULL,
  brake_temp_c            numeric(6,2)  NOT NULL,
  abs_fault_indicator     smallint      NOT NULL DEFAULT 0,
  brake_pedal_pos_percent numeric(5,2)  NOT NULL,
  wheel_speed_fl_kph      numeric(6,2)  NOT NULL,
  wheel_speed_fr_kph      numeric(6,2)  NOT NULL,
  wheel_speed_rl_kph      numeric(6,2)  NOT NULL,
  wheel_speed_rr_kph      numeric(6,2)  NOT NULL,
  battery_voltage_v       numeric(5,2)  NOT NULL,
  battery_current_a       numeric(6,2)  NOT NULL,
  battery_temp_c          numeric(6,2)  NOT NULL,
  alternator_output_v     numeric(5,2)  NOT NULL,
  battery_charge_percent  numeric(5,2)  NOT NULL,
  battery_health_percent  numeric(5,2)  NOT NULL,
  vehicle_speed_kph       numeric(6,2)  NOT NULL,
  ambient_temp_c          numeric(5,2)  NOT NULL,
  humidity_percent        numeric(5,2)  NOT NULL,
  extra_attributes        jsonb,
  recorded_by             bigint,
  created_at              timestamptz   NOT NULL DEFAULT now(),
  CONSTRAINT telemetry_readings_pkey PRIMARY KEY (telemetry_id),
  CONSTRAINT fk_telemetry_vehicle FOREIGN KEY (vehicle_id) REFERENCES public.vehicles (vehicle_id) ON DELETE CASCADE,
  CONSTRAINT fk_telemetry_user FOREIGN KEY (recorded_by) REFERENCES public.users (user_id) ON DELETE SET NULL,
  CONSTRAINT ck_telemetry_abs CHECK (abs_fault_indicator IN (0, 1)),
  CONSTRAINT ck_telemetry_non_negative CHECK (
    odometer_reading >= 0 AND engine_rpm >= 0 AND engine_hours >= 0 AND brake_pad_wear_mm >= 0
    AND vehicle_speed_kph >= 0 AND oil_pressure_psi >= 0 AND fuel_consumption_lph >= 0
  ),
  CONSTRAINT ck_telemetry_percents CHECK (
    fuel_level_percent BETWEEN 0 AND 100 AND engine_load_percent BETWEEN 0 AND 100
    AND throttle_pos_percent BETWEEN 0 AND 100 AND brake_pedal_pos_percent BETWEEN 0 AND 100
    AND battery_charge_percent BETWEEN 0 AND 100 AND battery_health_percent BETWEEN 0 AND 100
    AND humidity_percent BETWEEN 0 AND 100
  )
);
CREATE INDEX ix_telemetry_user ON public.telemetry_readings (recorded_by);
CREATE INDEX ix_telemetry_vehicle ON public.telemetry_readings (vehicle_id, created_at);

CREATE TABLE public.maintenance_predictions (
  prediction_id     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vehicle_id        bigint       NOT NULL,
  telemetry_id      bigint,
  target            varchar(30)  NOT NULL DEFAULT 'failure_imminent',
  prediction        smallint     NOT NULL,
  needs_maintenance boolean      NOT NULL,
  probability       numeric(7,6),
  model_name        varchar(60)  NOT NULL DEFAULT 'failure_imminent_rf',
  predicted_by      bigint,
  predicted_at      timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT maintenance_predictions_pkey PRIMARY KEY (prediction_id),
  CONSTRAINT fk_predictions_vehicle FOREIGN KEY (vehicle_id) REFERENCES public.vehicles (vehicle_id) ON DELETE CASCADE,
  CONSTRAINT fk_predictions_telemetry FOREIGN KEY (telemetry_id) REFERENCES public.telemetry_readings (telemetry_id) ON DELETE SET NULL,
  CONSTRAINT fk_predictions_user FOREIGN KEY (predicted_by) REFERENCES public.users (user_id) ON DELETE SET NULL,
  CONSTRAINT ck_predictions_probability CHECK (probability IS NULL OR (probability >= 0 AND probability <= 1)),
  CONSTRAINT ck_predictions_target CHECK (target IN ('failure_imminent', 'engine_failure_imminent', 'brake_issue_imminent', 'battery_issue_imminent')),
  CONSTRAINT ck_predictions_value CHECK (prediction IN (0, 1))
);
CREATE INDEX ix_predictions_risk ON public.maintenance_predictions (target, probability);
CREATE INDEX ix_predictions_telemetry ON public.maintenance_predictions (telemetry_id);
CREATE INDEX ix_predictions_user ON public.maintenance_predictions (predicted_by);
CREATE INDEX ix_predictions_vehicle ON public.maintenance_predictions (vehicle_id, target, predicted_at);

CREATE TABLE public.maintenances (
  maintenance_id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code             varchar(40)  NOT NULL,
  vehicle_id       bigint       NOT NULL,
  maintenance_type varchar(60)  NOT NULL,
  scheduled_date   date         NOT NULL,
  performed_at     date,
  finished         boolean      NOT NULL DEFAULT false,
  notes            varchar(200),
  prediction_id    bigint,
  created_by       bigint,
  created_at       timestamptz  NOT NULL DEFAULT now(),
  updated_at       timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT maintenances_pkey PRIMARY KEY (maintenance_id),
  CONSTRAINT uq_maintenances_code UNIQUE (code),
  CONSTRAINT fk_maintenances_vehicle FOREIGN KEY (vehicle_id) REFERENCES public.vehicles (vehicle_id) ON DELETE CASCADE,
  CONSTRAINT fk_maintenances_prediction FOREIGN KEY (prediction_id) REFERENCES public.maintenance_predictions (prediction_id) ON DELETE SET NULL,
  CONSTRAINT fk_maintenances_created_by FOREIGN KEY (created_by) REFERENCES public.users (user_id) ON DELETE SET NULL
);
CREATE INDEX ix_maintenances_created_by ON public.maintenances (created_by);
CREATE INDEX ix_maintenances_prediction ON public.maintenances (prediction_id);
CREATE INDEX ix_maintenances_schedule ON public.maintenances (scheduled_date);
CREATE INDEX ix_maintenances_vehicle ON public.maintenances (vehicle_id, finished);

CREATE TABLE public.fuel_records (
  fuel_record_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code           varchar(40)  NOT NULL,
  vehicle_id     bigint       NOT NULL,
  fuel_type      varchar(10)  NOT NULL,
  notes          varchar(120),
  recorded_by    bigint,
  recorded_at    timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT fuel_records_pkey PRIMARY KEY (fuel_record_id),
  CONSTRAINT uq_fuel_records_code UNIQUE (code),
  CONSTRAINT fk_fuel_records_vehicle FOREIGN KEY (vehicle_id) REFERENCES public.vehicles (vehicle_id) ON DELETE CASCADE,
  CONSTRAINT fk_fuel_records_user FOREIGN KEY (recorded_by) REFERENCES public.users (user_id) ON DELETE SET NULL,
  CONSTRAINT ck_fuel_records_type CHECK (fuel_type IN ('Gasoline', 'Diesel'))
);
CREATE INDEX ix_fuel_records_user ON public.fuel_records (recorded_by);
CREATE INDEX ix_fuel_records_vehicle ON public.fuel_records (vehicle_id, recorded_at);

CREATE TABLE public.audit_logs (
  audit_id    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code        varchar(40)  NOT NULL,
  action      varchar(40)  NOT NULL,
  user_id     bigint,
  actor_label varchar(10),
  detail      varchar(180),
  ip_address  varchar(45),
  created_at  timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (audit_id),
  CONSTRAINT uq_audit_code UNIQUE (code),
  CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES public.users (user_id) ON DELETE SET NULL,
  CONSTRAINT ck_audit_actor CHECK (actor_label IS NULL OR actor_label IN ('system', 'guest'))
);
CREATE INDEX ix_audit_action ON public.audit_logs (action, created_at);
CREATE INDEX ix_audit_created ON public.audit_logs (created_at);
CREATE INDEX ix_audit_user ON public.audit_logs (user_id, created_at);

-- -----------------------------------------------------------------------------
-- Triggers
-- -----------------------------------------------------------------------------

CREATE TRIGGER trg_bookings_before_insert BEFORE INSERT ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.fn_bookings_before_insert();
CREATE TRIGGER trg_bookings_before_update BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.fn_bookings_before_update();
CREATE TRIGGER trg_bookings_updated_at BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_drivers_before_write BEFORE INSERT OR UPDATE ON public.drivers FOR EACH ROW EXECUTE FUNCTION public.fn_drivers_before_write();
CREATE TRIGGER trg_drivers_updated_at BEFORE UPDATE ON public.drivers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_maintenances_updated_at BEFORE UPDATE ON public.maintenances FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_payments_before_insert BEFORE INSERT ON public.payments FOR EACH ROW EXECUTE FUNCTION public.fn_payments_before_insert();
CREATE TRIGGER trg_ratings_before_insert BEFORE INSERT ON public.ratings FOR EACH ROW EXECUTE FUNCTION public.fn_ratings_before_insert();
CREATE TRIGGER trg_registrations_updated_at BEFORE UPDATE ON public.vehicle_registrations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_threads_updated_at BEFORE UPDATE ON public.message_threads FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_vehicles_updated_at BEFORE UPDATE ON public.vehicles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -----------------------------------------------------------------------------
-- Reporting views
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.v_booking_status_counts AS
SELECT status, count(*) AS bookings
FROM public.bookings
GROUP BY status;

CREATE OR REPLACE VIEW public.v_dashboard_summary AS
SELECT
  (SELECT count(*) FROM public.bookings) AS bookings,
  (SELECT count(*) FROM public.bookings WHERE status = 'pending') AS incoming_bookings,
  (SELECT count(*) FROM public.bookings WHERE status = 'return_requested') AS pending_returns,
  (SELECT count(*) FROM public.vehicles WHERE deleted_at IS NULL) AS vehicles,
  (SELECT count(*) FROM public.users WHERE role = 'customer') AS customers,
  (SELECT count(*) FROM public.drivers WHERE status = 'active' AND deleted_at IS NULL) AS active_drivers,
  (SELECT count(*) FROM public.maintenances WHERE finished = false) AS open_maintenance,
  (SELECT count(*) FROM public.message_threads WHERE unread_staff = true) AS unread_threads,
  (SELECT COALESCE(sum(total), 0) FROM public.bookings
    WHERE payment_status = 'paid' AND status NOT IN ('rejected', 'cancelled')) AS revenue;

CREATE OR REPLACE VIEW public.v_fleet_repair_stats AS
SELECT
  count(*) AS total_vehicles,
  count(*) FILTER (WHERE status = 'maintenance') AS in_repair,
  COALESCE(round(100.0 * count(*) FILTER (WHERE status = 'maintenance') / NULLIF(count(*), 0)), 0) AS repair_percent
FROM public.vehicles
WHERE deleted_at IS NULL;

CREATE OR REPLACE VIEW public.v_registration_renewals_due AS
SELECT r.registration_id, r.vehicle_id, v.name, r.plate_number, r.next_reg_renewal,
       (r.next_reg_renewal - CURRENT_DATE) AS days_left
FROM public.vehicle_registrations r
JOIN public.vehicles v ON v.vehicle_id = r.vehicle_id
WHERE v.deleted_at IS NULL;

CREATE OR REPLACE VIEW public.v_revenue_by_vehicle_type AS
SELECT v.type, sum(b.total) AS revenue, count(*) AS paid_bookings
FROM public.bookings b
JOIN public.vehicles v ON v.vehicle_id = b.vehicle_id
WHERE b.payment_status = 'paid' AND b.status NOT IN ('rejected', 'cancelled')
GROUP BY v.type;

CREATE OR REPLACE VIEW public.v_vehicle_latest_prediction AS
SELECT prediction_id, vehicle_id, telemetry_id, target, prediction, needs_maintenance,
       probability, model_name, predicted_by, predicted_at
FROM (
  SELECT mp.*, row_number() OVER (
    PARTITION BY mp.vehicle_id, mp.target ORDER BY mp.predicted_at DESC, mp.prediction_id DESC
  ) AS rn
  FROM public.maintenance_predictions mp
) p
WHERE rn = 1;

CREATE OR REPLACE VIEW public.v_vehicle_latest_telemetry AS
SELECT *
FROM (
  SELECT tr.*, row_number() OVER (
    PARTITION BY tr.vehicle_id ORDER BY tr.created_at DESC, tr.telemetry_id DESC
  ) AS rn
  FROM public.telemetry_readings tr
) t
WHERE rn = 1;

CREATE OR REPLACE VIEW public.v_vehicle_rating_summary AS
SELECT v.vehicle_id, v.code, count(r.rating_id) AS rating_count,
       COALESCE(round(avg(r.stars), 1), 0) AS rating_average
FROM public.vehicles v
LEFT JOIN public.ratings r ON r.vehicle_id = v.vehicle_id
WHERE v.deleted_at IS NULL
GROUP BY v.vehicle_id, v.code;

-- -----------------------------------------------------------------------------
-- Row level security: enabled with no policies, so Supabase's public API
-- (anon / authenticated roles) cannot read or write these tables. The Laravel
-- backend connects as the table owner and is not affected.
-- -----------------------------------------------------------------------------

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_lockouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_features ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_renter_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.thread_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fuel_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
